# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .erb # assets/javascripts
    - .js
    - .jsx
    - .sass # assets/stylesheets
    - .scss
    - .css
    - .svg # assets/images
    - .png
    - .gif
    - .jpeg
    - .jpg
    - .mp4 # assets/videos
    - .webm

development:
  <<: *default

  dev_server:
    host: 0.0.0.0
    port: 8080
    https: false

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
